[build]
  base = "web"
  command = "npm --workspace mapleland-party-web run build"
  publish = ".next"

[[redirects]]
  from = "/api/*"
  to = "https://eastern-colene-maplelandqueue-3b264458.koyeb.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/auth/*"
  to = "https://eastern-colene-maplelandqueue-3b264458.koyeb.app/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/health"
  to = "https://eastern-colene-maplelandqueue-3b264458.koyeb.app/health"
  status = 200
  force = true
